/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PetShop.management.system;

import java.util.ArrayList;
import model.Category;
import model.Product;
import DataAccessObject.CategoryDao;
import java.util.Iterator;
import DataAccessObject.ProductDao;

/**
 *
 * @author Nihal
 */
public class AddNewProduct extends javax.swing.JFrame {

    /**
     * Creates new form AddNewProduct
     */
    public AddNewProduct() {
        initComponents();
        btnSave.setEnabled(false);
    }
    public void validateFields(){
        String articleNo = txtArticleNo.getText();
        String quantity = txtQuantity.getText();
        String mrp = txtMrp.getText();
        String pp= txtPp.getText();
        Boolean flag=false;
        try{
            Integer.parseInt(quantity);
            Integer.parseInt(mrp);
            Integer.parseInt(pp);
            flag=true;
        }
        catch(NumberFormatException e){
            flag=false;
            //Errortext.setText("Please enter an Integer Value");
        }
        if(!articleNo.equals("") && !quantity.equals("") && !mrp.equals("") && !pp.equals("") && !flag.equals(false))
            btnSave.setEnabled(true);
        else{
            btnSave.setEnabled(false);
          //  Errortext.setText("Please enter an Integer Value");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtArticleNo = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtMrp = new javax.swing.JTextField();
        txtPp = new javax.swing.JTextField();
        txtBrand = new javax.swing.JComboBox();
        QTypeCombo = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        Errortext = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBrand1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(380, 150));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new product.png"))); // NOI18N
        jLabel1.setText("Add Product for Pet");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 29, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Product Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 109, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Pet Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 191, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("MRP                        ₹");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Purchasing Price    ₹");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Q Type");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        txtArticleNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtArticleNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtArticleNoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtArticleNoKeyReleased(evt);
            }
        });
        getContentPane().add(txtArticleNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 106, 250, -1));

        txtQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantityKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 188, 250, -1));

        txtMrp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMrp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMrpKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMrpKeyReleased(evt);
            }
        });
        getContentPane().add(txtMrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 250, -1));

        txtPp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPpKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPpKeyReleased(evt);
            }
        });
        getContentPane().add(txtPp, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 250, -1));

        txtBrand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBrandKeyPressed(evt);
            }
        });
        getContentPane().add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 250, -1));

        QTypeCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Packet(s)", "Piece", "Box(s)", "Gram", "Kg" }));
        getContentPane().add(QTypeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 250, -1));

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        btnSave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSaveKeyPressed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        btnClear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnClearKeyPressed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        Errortext.setText("All Fields Compulsary");
        getContentPane().add(Errortext, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/MiniPage.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtBrand1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBrand1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBrand1KeyPressed(evt);
            }
        });
        getContentPane().add(txtBrand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(298, 147, 250, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddNewProduct().setVisible(true);
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtArticleNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArticleNoKeyReleased
        // TODO add your handling code here:
        validateFields();
    }//GEN-LAST:event_txtArticleNoKeyReleased

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        // TODO add your handling code here:
        validateFields();
        try{
            Integer.parseInt(txtQuantity.getText());
            
        }
        catch(NumberFormatException e){
            Errortext.setText("<html><b>Please enter an Integer Value in Quantity , MRP & Purchasing Price</b></html>");
        }
    }//GEN-LAST:event_txtQuantityKeyReleased

    private void txtMrpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMrpKeyReleased
        // TODO add your handling code here:
        validateFields();
        try{
            Integer.parseInt(txtMrp.getText());
            
        }
        catch(NumberFormatException e){
            Errortext.setText("<html><b>Please enter an Integer Value in Quantity , MRP & Purchasing Price</b></html>");
        }
    }//GEN-LAST:event_txtMrpKeyReleased

    private void txtPpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPpKeyReleased
        // TODO add your handling code here:
        validateFields();
        try{
            Integer.parseInt(txtPp.getText());
            
        }
        catch(NumberFormatException e){
            Errortext.setText("<html><b>Please enter an Integer Value in Quantity , MRP & Purchasing Price</b></html>");
        }
    }//GEN-LAST:event_txtPpKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        ArrayList<Category> list = CategoryDao.getAllRecords();
        Iterator<Category> itr = list.iterator();
        while(itr.hasNext()){
        Category categoryObj= itr.next();
        txtBrand.addItem(categoryObj.getName());
        }
    }//GEN-LAST:event_formComponentShown

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Product product= new Product();
        product.setName(txtArticleNo.getText());
        product.setBrand((String)txtBrand.getSelectedItem());
        product.setQuantity(txtQuantity.getText());
        product.setMrp(txtMrp.getText());
        product.setPp(txtPp.getText());
        product.setqType((String)QTypeCombo.getSelectedItem());
        ProductDao.save(product);
        setVisible(false);
        new AddNewProduct().setVisible(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtArticleNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArticleNoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==40)
            txtBrand.requestFocus();
    }//GEN-LAST:event_txtArticleNoKeyPressed

    private void txtBrandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrandKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==40)
            txtQuantity.requestFocus();
        if(evt.getKeyCode()==38)
            txtArticleNo.requestFocus();
    }//GEN-LAST:event_txtBrandKeyPressed

    private void txtQuantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==40)
            txtMrp.requestFocus();
        if(evt.getKeyCode()==38)
            txtBrand.requestFocus();
    }//GEN-LAST:event_txtQuantityKeyPressed

    private void txtMrpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMrpKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==40)
            txtPp.requestFocus();
        if(evt.getKeyCode()==38)
            txtQuantity.requestFocus();
    }//GEN-LAST:event_txtMrpKeyPressed

    private void txtPpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPpKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==40)
            btnSave.requestFocus();
        if(evt.getKeyCode()==38)
            txtMrp.requestFocus();
    }//GEN-LAST:event_txtPpKeyPressed

    private void btnSaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSaveKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==39)
            btnClear.requestFocus();
        if(evt.getKeyCode()==38)
            txtPp.requestFocus();
    }//GEN-LAST:event_btnSaveKeyPressed

    private void btnClearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnClearKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==37)
            btnSave.requestFocus();
        if(evt.getKeyCode()==38)
            txtPp.requestFocus();
    }//GEN-LAST:event_btnClearKeyPressed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void txtBrand1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrand1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrand1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Errortext;
    private javax.swing.JComboBox<String> QTypeCombo;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtArticleNo;
    private javax.swing.JComboBox txtBrand;
    private javax.swing.JComboBox txtBrand1;
    private javax.swing.JTextField txtMrp;
    private javax.swing.JTextField txtPp;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
