/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PetShop.management.system;

import DataAccessObject.CategoryDao;
import DataAccessObject.ProductDao;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.Category;
import model.Product;

/**
 *
 * @author Nihal
 */
public class ViewEditDeleteProduct extends javax.swing.JFrame {

    private Object product;

    /**
     * Creates new form ViewEditDeleteProduct
     */
    public ViewEditDeleteProduct() {
        initComponents();
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }

    public void validateField() {
        String ArticleNo = txtArticleNo.getText();
        String Brand = (String) txtBrand.getSelectedItem();
        String Quantity = txtQuantity.getText();
        String qType =(String) jComboBox1.getSelectedItem();
        String Mrp = txtMrp.getText();
        String Pp = txtPp.getText();
        Boolean flag=false;
        try{
            Integer.parseInt(Quantity);
            Integer.parseInt(Mrp);
            Integer.parseInt(Pp);
            flag=true;
        }
        catch(NumberFormatException e){
            flag=false;
            //Errortext.setText("Please enter an Integer Value");
        }
        if (!ArticleNo.equals("") && !Quantity.equals("") && !Mrp.equals("") && !Pp.equals("")&& !flag.equals(false)) {
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
        } else {
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblid = new javax.swing.JLabel();
        txtArticleNo = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtMrp = new javax.swing.JTextField();
        txtPp = new javax.swing.JTextField();
        txtBrand = new javax.swing.JComboBox();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Errortext = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png"))); // NOI18N
        jLabel1.setText("View,Edit & Delete Product");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 10, 30, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 164, 32, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Product Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 202, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Brand");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 243, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 284, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("MRP                                     ₹");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Purchasing Price                 ₹");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("QType");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Packet(s)", "Box(s)", "Gram", "Kg" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 300, -1));

        lblid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblid.setText("00");
        getContentPane().add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 164, 300, -1));

        txtArticleNo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtArticleNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArticleNoActionPerformed(evt);
            }
        });
        txtArticleNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtArticleNoKeyReleased(evt);
            }
        });
        getContentPane().add(txtArticleNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 199, 300, -1));

        txtQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQuantityKeyReleased(evt);
            }
        });
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 281, 300, -1));

        txtMrp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMrp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMrpKeyReleased(evt);
            }
        });
        getContentPane().add(txtMrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 300, -1));

        txtPp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtPp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPpKeyReleased(evt);
            }
        });
        getContentPane().add(txtPp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 300, -1));

        txtBrand.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 240, 300, -1));

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, -1));

        txtClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear.png"))); // NOI18N
        txtClear.setText("Clear");
        txtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClearActionPerformed(evt);
            }
        });
        getContentPane().add(txtClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, -1, -1));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Brand", "Quantity", "QType", "MRP", "Purchase Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(779, 138, 490, -1));

        Errortext.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Errortext, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 111, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AllPages.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtArticleNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArticleNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArticleNoActionPerformed

    private void txtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClearActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ViewEditDeleteProduct().setVisible(true);

    }//GEN-LAST:event_txtClearActionPerformed

    private void txtArticleNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArticleNoKeyReleased
        // TODO add your handling code here:
        validateField();
    }//GEN-LAST:event_txtArticleNoKeyReleased

    private void txtQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyReleased
        // TODO add your handling code here:
        validateField();
        try{
            Integer.parseInt(txtQuantity.getText());
            
        }
        catch(NumberFormatException e){
            Errortext.setText("<html><b>Please enter an Integer Value in Quantity , MRP & Purchasing Price</b></html>");
        }
    }//GEN-LAST:event_txtQuantityKeyReleased

    private void txtMrpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMrpKeyReleased
        // TODO add your handling code here:
        validateField();
        try{
            Integer.parseInt(txtMrp.getText());
            
        }
        catch(NumberFormatException e){
            Errortext.setText("<html><b>Please enter an Integer Value in Quantity , MRP & Purchasing Price</b></html>");
        }
    }//GEN-LAST:event_txtMrpKeyReleased

    private void txtPpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPpKeyReleased
        // TODO add your handling code here:
        validateField();
        try{
            Integer.parseInt(txtPp.getText());
            
        }
        catch(NumberFormatException e){
            Errortext.setText("<html><b>Please enter an Integer Value in Quantity , MRP & Purchasing Price</b></html>");
        }
    }//GEN-LAST:event_txtPpKeyReleased

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        Product product = new Product();
        int id = Integer.parseInt(lblid.getText());
        product.setId(id);
        product.setName(txtArticleNo.getText());
        product.setBrand((String) txtBrand.getSelectedItem());
        product.setQuantity(txtQuantity.getText());
        product.setqType((String)jComboBox1.getSelectedItem());
        product.setMrp(txtMrp.getText());
        product.setPp(txtPp.getText());
        ProductDao.update(product);
        setVisible(false);
        new ViewEditDeleteProduct().setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        ArrayList<Product> list = ProductDao.getAllRecords();
        Iterator<Product> itr = list.iterator();
        while (itr.hasNext()) {
            Product productObj = itr.next();
            dtm.addRow(new Object[]{productObj.getId(), productObj.getName(), productObj.getBrand(), productObj.getQuantity(),productObj.getqType() ,productObj.getMrp(), productObj.getPp()});
        }
    }//GEN-LAST:event_formComponentShown

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int Index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        String id = model.getValueAt(Index, 0).toString();
        lblid.setText(id);
        String ArticleNo = model.getValueAt(Index, 1).toString();
        txtArticleNo.setText(ArticleNo);
        String Brand = model.getValueAt(Index, 2).toString();
        String Quantity = model.getValueAt(Index, 3).toString();
        txtQuantity.setText(Quantity);
        String qType = model.getValueAt(Index, 4).toString();
        String Mrp = model.getValueAt(Index, 5).toString();
        txtMrp.setText(Mrp);
        String Pp = model.getValueAt(Index, 6).toString();
        txtPp.setText(Pp);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
        txtBrand.removeAllItems();
        txtBrand.addItem(Brand);
        ArrayList<Category> categoryList = CategoryDao.getAllRecords();
        Iterator<Category> categoryItr = categoryList.iterator();
        while (categoryItr.hasNext()) {
            Category categoryObj = categoryItr.next();
            if (!categoryObj.getName().equals(Brand)) {
                txtBrand.addItem(categoryObj.getName());
            }
        }
        /*
        jComboBox1.removeAllItems();
        jComboBox1.addItem(qType);
        ArrayList<Product> productList = ProductDao.getQtype();
        Iterator<Product> productItr = productList.iterator();
        while(productItr.hasNext()){
            Product productObbj = productItr.next();
            if(!productObbj.getqType().equals(qType)){
                jComboBox1.addItem(productObbj.getqType());
            }
        }*/
        

    }//GEN-LAST:event_jTable1MouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String id = lblid.getText();
        int a = JOptionPane.showConfirmDialog(null, "Do you Want to Delete the Product?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            ProductDao.delete(id);
            setVisible(false);
            new ViewEditDeleteProduct().setVisible(true);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEditDeleteProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEditDeleteProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Errortext;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblid;
    private javax.swing.JTextField txtArticleNo;
    private javax.swing.JComboBox txtBrand;
    private javax.swing.JButton txtClear;
    private javax.swing.JTextField txtMrp;
    private javax.swing.JTextField txtPp;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
